# Site settings
title: Institute of Information and Communications Technology
header_title: IICT
email: your-email@domain.com
description: Include description here
baseurl: "" # none so far
url: "127.0.0.1" # test site base hostname & protocol
twitter_username: none
github_username:  none
facebook_username:  none

# Build settings
markdown: kramdown
